http: 
  port: "8081"
  
american:
  host: "training4-american-api-aly.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "fad0dc9c3eda4d5fae52780a2ccb0bc2"
  client_secret: "88f6AE9eDBf04E8093655EC68D99Aca9"
  
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"